/*
Finnhub API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finnhub

import (
	"encoding/json"
)

// NewsroomArticle struct for NewsroomArticle
type NewsroomArticle struct {
	// Published time in <code>YYYY-MM-DD HH:MM:SS</code> format (EST timezone).
	AtDate *string `json:"atDate,omitempty"`
	// Title.
	Title *string `json:"title,omitempty"`
	// URL to download the full text data.
	FullText *string `json:"fullText,omitempty"`
	// Original URL.
	Url *string `json:"url,omitempty"`
}

// NewNewsroomArticle instantiates a new NewsroomArticle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewsroomArticle() *NewsroomArticle {
	this := NewsroomArticle{}
	return &this
}

// NewNewsroomArticleWithDefaults instantiates a new NewsroomArticle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewsroomArticleWithDefaults() *NewsroomArticle {
	this := NewsroomArticle{}
	return &this
}

// GetAtDate returns the AtDate field value if set, zero value otherwise.
func (o *NewsroomArticle) GetAtDate() string {
	if o == nil || o.AtDate == nil {
		var ret string
		return ret
	}
	return *o.AtDate
}

// GetAtDateOk returns a tuple with the AtDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsroomArticle) GetAtDateOk() (*string, bool) {
	if o == nil || o.AtDate == nil {
		return nil, false
	}
	return o.AtDate, true
}

// HasAtDate returns a boolean if a field has been set.
func (o *NewsroomArticle) HasAtDate() bool {
	if o != nil && o.AtDate != nil {
		return true
	}

	return false
}

// SetAtDate gets a reference to the given string and assigns it to the AtDate field.
func (o *NewsroomArticle) SetAtDate(v string) {
	o.AtDate = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *NewsroomArticle) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsroomArticle) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *NewsroomArticle) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *NewsroomArticle) SetTitle(v string) {
	o.Title = &v
}

// GetFullText returns the FullText field value if set, zero value otherwise.
func (o *NewsroomArticle) GetFullText() string {
	if o == nil || o.FullText == nil {
		var ret string
		return ret
	}
	return *o.FullText
}

// GetFullTextOk returns a tuple with the FullText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsroomArticle) GetFullTextOk() (*string, bool) {
	if o == nil || o.FullText == nil {
		return nil, false
	}
	return o.FullText, true
}

// HasFullText returns a boolean if a field has been set.
func (o *NewsroomArticle) HasFullText() bool {
	if o != nil && o.FullText != nil {
		return true
	}

	return false
}

// SetFullText gets a reference to the given string and assigns it to the FullText field.
func (o *NewsroomArticle) SetFullText(v string) {
	o.FullText = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *NewsroomArticle) GetUrl() string {
	if o == nil || o.Url == nil {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsroomArticle) GetUrlOk() (*string, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *NewsroomArticle) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *NewsroomArticle) SetUrl(v string) {
	o.Url = &v
}

func (o NewsroomArticle) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AtDate != nil {
		toSerialize["atDate"] = o.AtDate
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	if o.FullText != nil {
		toSerialize["fullText"] = o.FullText
	}
	if o.Url != nil {
		toSerialize["url"] = o.Url
	}
	return json.Marshal(toSerialize)
}

type NullableNewsroomArticle struct {
	value *NewsroomArticle
	isSet bool
}

func (v NullableNewsroomArticle) Get() *NewsroomArticle {
	return v.value
}

func (v *NullableNewsroomArticle) Set(val *NewsroomArticle) {
	v.value = val
	v.isSet = true
}

func (v NullableNewsroomArticle) IsSet() bool {
	return v.isSet
}

func (v *NullableNewsroomArticle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewsroomArticle(val *NewsroomArticle) *NullableNewsroomArticle {
	return &NullableNewsroomArticle{value: val, isSet: true}
}

func (v NullableNewsroomArticle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewsroomArticle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


