/*
Finnhub API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

package finnhub

import (
	"encoding/json"
)

// ETFAllocationData struct for ETFAllocationData
type ETFAllocationData struct {
	LargeBlend  *float32 `json:"largeBlend,omitempty"`
	LargeGrowth *float32 `json:"largeGrowth,omitempty"`
	LargeValue  *float32 `json:"largeValue,omitempty"`
	MidBlend    *float32 `json:"midBlend,omitempty"`
	MidGrowth   *float32 `json:"midGrowth,omitempty"`
	MidValue    *float32 `json:"midValue,omitempty"`
	SmallBlend  *float32 `json:"smallBlend,omitempty"`
	SmallGrowth *float32 `json:"smallGrowth,omitempty"`
	SmallValue  *float32 `json:"smallValue,omitempty"`
}

// NewETFAllocationData instantiates a new ETFAllocationData object
func NewETFAllocationData() *ETFAllocationData {
	this := ETFAllocationData{}
	return &this
}

// NewETFAllocationDataWithDefaults instantiates a new ETFAllocationData object
func NewETFAllocationDataWithDefaults() *ETFAllocationData {
	this := ETFAllocationData{}
	return &this
}

func (o ETFAllocationData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.LargeBlend != nil {
		toSerialize["largeBlend"] = o.LargeBlend
	}
	if o.LargeGrowth != nil {
		toSerialize["largeGrowth"] = o.LargeGrowth
	}
	if o.LargeValue != nil {
		toSerialize["largeValue"] = o.LargeValue
	}
	if o.MidBlend != nil {
		toSerialize["midBlend"] = o.MidBlend
	}
	if o.MidGrowth != nil {
		toSerialize["midGrowth"] = o.MidGrowth
	}
	if o.MidValue != nil {
		toSerialize["midValue"] = o.MidValue
	}
	if o.SmallBlend != nil {
		toSerialize["smallBlend"] = o.SmallBlend
	}
	if o.SmallGrowth != nil {
		toSerialize["smallGrowth"] = o.SmallGrowth
	}
	if o.SmallValue != nil {
		toSerialize["smallValue"] = o.SmallValue
	}
	return json.Marshal(toSerialize)
}

// ETFAllocation struct for ETFAllocation
type ETFAllocation struct {
	Data   *ETFAllocationData `json:"data,omitempty"`
	Symbol *string            `json:"symbol,omitempty"`
}

// NewETFAllocation instantiates a new ETFAllocation object
func NewETFAllocation() *ETFAllocation {
	this := ETFAllocation{}
	return &this
}

// NewETFAllocationWithDefaults instantiates a new ETFAllocation object
func NewETFAllocationWithDefaults() *ETFAllocation {
	this := ETFAllocation{}
	return &this
}

func (o ETFAllocation) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Symbol != nil {
		toSerialize["symbol"] = o.Symbol
	}
	return json.Marshal(toSerialize)
}
